### ISSUE TITLE
Transition to new state from entry signal

### ISSUE THREAD

**Issue by vChavezB** [QuantumLeaps/qpcpp#11]
I am refactoring a project with a polling state machine and I found an issue, which I am not sure if it's because I just started using the QP framework.

I have a state that should transition immediately to a state depending on some guards that were set/unset via the entry action. I tried the following:

````cpp
bool DummyGuard;
Q_STATE_DEF(MyAO, State1) 
{
    QP::QState status_;
    switch (e->sig) {
        case Q_ENTRY_SIG: 
          {
                /*
                Here should be the logic that sets/unsets guard
               */
               if(DummyGuard)
               {
                    status_ = tran(&state2);
               }
               else
               {
                    status_ = tran(&state1);
               }
                break;
        }
        default: 
       {
            status_ = super(&MyOtherState);
            break;
        }
    }
    return status_;
}
````

This did not work, and the state that was executed afterward is the same `state1`. I started debugging the framework and I found that `QHsm::m_temp.fun` is assigned again the top state `MyOtherState`, which overrides the value assigned via ` tran(&state2)` or `tran(&state3)`. 

What I ended up doing is creating an artificial signal that is executed in the entry action, and afterward in this signal is where I do the logic to change to the next state.

````cpp
/* Abritriary number for Artificial signal.
  This number is actually in an enum with all the other signals
 */
int SIG_ARTIFICIAL=6; 
static constexpr QP::QEvt ArtificialEvt= {.sig=static_cast<QP::QSignal>(SIG_ARTIFICIAL),
                                                  .poolId_=0,
                                                  .refCtr_=0};
bool DummyGuard;
Q_STATE_DEF(MyAO, State1) 
{
    QP::QState status_;
    switch (e->sig) {
        case Q_ENTRY_SIG: 
          {
               POST(&ArtificialEvt,this);
                break;
        }
       case SIG_ARTIFICIAL:
               if(DummyGuard)
               {
                    status_ = tran(&state2);
               }
               else
               {
                    status_ = tran(&state1);
               }
               break;
        default: 
       {
            status_ = super(&MyOtherState);
            break;
        }
    }
    return status_;
}
````

Based on this small test I am not sure if this is the correct way to accomplish this objective with the QP Framework or if there is an easier way to do this without having to create a signal+event. I am also not sure if this would be UML compliant . Speaking about UML would I need to define a Signal to transition or could I have a transition that does not depend on a signal (e.g., the initial transition).

I am asking this because the project is based on a protocol specification that has some state machines with this type of state chart notation where the state does some logic in the entry action and then depending on guards it will change to another state. 

Thanks in advance for any feedback on this discussion
Victor

**Comment by quantum-leaps** [comment]
Hi Victor,

> I have a state that should transition immediately to a state depending on some guards...

This seems to be a common case of confusing a statechart with a flowchart, at least in this part. That particular "state" is not really waiting for any new events -- it is simply a stage in processing (flowchart box).

> I tried the following (transition from an entry action... This did not work.

Of course it didn't work. Transitions are not allowed in state entry/exit actions. Perhaps it will be clearer if you tried to draw such a thing in a state diagram... If you cannot draw it, it is probably wrong.

> What I ended up doing is creating an artificial signal...

Self-posting of an invented signal has its place in state machine designs, but the case of "flowchart-style states" is not the best use of it. Yes, sure, the self-posted event would provide the needed trigger for the transition out of such a "state", but it only covers up the bad design. A better way is to eliminate such a "state" and replace it with a transition (with guards), because this is what it really is.

Please note that the state machine gets new information only through new events. In the case of a self-posting of an event you don't get any new information. All the information to take the right transition was available already before, so why don't you take the right transition as soon as possible.

> I am asking this because the project is based on a protocol specification that has some state machines with this type...

My first recommendation would be to eliminate as many of such "flowchart-style states" as possible and replace them with transitions, because that's what they are. I understand that you might be concerned with repetitions, if there are many incoming transitions to such "states", because then you need to repeat the outgoing transition (with guards) just as many times. But if you have only one or two incoming transitions, it should be a better tradeoff.

Self-posting of an invented trigger would work too, but it is inferior, because the continuation of a given transition is not clear from the state machine design. That information is hidden behind the invented event. So, here, to help in understanding the intent, I would recommend to use a naming convention for the invented event and call it "CONTINUATION_SIG" or something similar. This is because it corresponds to the "continuation event in UML statecharts" (See UML Specification, Section 14.2.3.8.3 "Completion Transitions and completion events").

Finally, it is always a good exercise to actually draw the state diagram that you are re-coding in QP. This should help you clarify the design in your mind and avoid the wrong ideas (if you can't draw it, it's probably wrong...) The next logical step after that would be to use the QM visual tool to draw your diagrams there and let the tool generate the code for you. That way, you could eliminate stupid coding mistakes. 

I hope that my comments make sense to you.

--MMS

**Comment by vChavezB** [comment]
Thanks for the detailed explanation and thoughts about this issue. Just to give a little bit more context the actual specification I am working with is  IEC 61131-9. It's better known as the IO-Link protocol which is used for sensors and actuators in automation systems.

 >This is because it corresponds to the "continuation event in UML statecharts" (See UML Specification, Section 14.2.3.8.3 "Completion Transitions and completion events").

I think this type of event would describe the situation of this issue.  According to the section:

>The event that enables this trigger is called a completion event and it signifies that all Behaviors associated with the source State of the completion Transition have completed execution.

Attached is an image of an example of what I mean from the IO-Link specification v1.1.3 (Figure 72):

<img src="https://i.imgur.com/eVDsT0K.png" data-canonical-src="https://i.imgur.com/eVDsT0K.png" width="300" height="200" />

In this image, the state `CheckCompV10_21` executes the do action, and after completing the action it transitions out of the substate machine depending on the guard conditions. From this example, I have a question. How could I model a do-action with the QP framework?

>Finally, it is always a good exercise to actually draw the state diagram that you are re-coding in QP.

As the state diagrams are based directly on the diagrams from the IO-Link spec, I did not model the system with QM. It would definitely help reduce stupid mistakes as you mentioned but the spec consists of around 16 state machines with nested substate machines. For this reason, I opted to understand how the framework works in general and modify the template models to know how the code is generated by the QM GUI.

I know this is not part of the open issue in this post but the last paragraph made me realize something. In general, there are 16 state machines for communication with one device (e.g., a sensor or actuator). So that means I need 16 Active Objects (AO) per device. I plan to work with 4 devices, which would mean I need 16 AO * 4 = 64 AO. 

This would be over the limit which according to the documentation is 63. Is there a design reason why the framework cannot use more AOs? Will something break if  `QF_MAX_ACTIVE>63` or lose performance? Or is this merely restricted to be compatible with the OS ports ( which some of them have task priority limited to 63 or less)?

Finally, thanks a lot for the last previous detailed answer and thoughts. I am planning to use your framework for future projects at the university with our students, as I think this is a relevant topic for Industrial communication and automation. I also work with the IEC 61131-3 standard where I teach PLC programming. It might be fun for me to check if a similar framework can be implemented for CODESYS.

Regards,
Victor

**Comment by quantum-leaps** [comment]
> In general, there are 16 state machines for communication with one device (e.g., a sensor or actuator). So that means I need 16 Active Objects (AO) per device...

Not necessarily. Many stateful components can be simply passive state machines (subclasses of QP::QHsm) and NOT active objects (subclasses of QP::QActive). This is why the QP framework has a separate class [QP::QHsm and its subclass QP::QActive](https://www.state-machine.com/qpcpp/struct.html#classes ). Specifically, I suspect that the 16 state machines inside each device don't all need a separate thread of execution and a separate event queue, so they could be such passive stateful components of just one active object. This means that you can have hundreds or thousands of passive state machines in a QP application.

Please take a look at the ["Orthogonal Component" state pattern](https://www.state-machine.com/doc/Pattern_Orthogonal.pdf). As usual, examples of the "Orthogonal Component" state pattern are provided:

- qpcpp\examples\workstation\comp -- The motivating example from the pattern description
- qpcpp\examples\workstation\dpp-comp - "Dining Philosophers Problem", where the Philosophers are "Orthogonal Components" of the Table active object.

> I also work with the IEC 61131-3 standard where I teach PLC programming.

Yeah, the French tend to overcomplicate the specs... (Oops, I hope you're not French...)

--MMS

**Comment by vChavezB** [comment]
> Specifically, I suspect that the 16 state machines inside each device don't all need a separate thread of execution and a separate event queue, so they could be such passive stateful 
 
Thanks, that helped me understand how to use `QP::QHsm` and `QP::Active.` I was thinking of having an active object per state machine but I would only need an Active Object, that processes Asynch events. Then the Active object can dispatch the passive `QP::QHsm`  state machines.
