### ISSUE TITLE
QHsm::isIn should support calls from super state

### ISSUE THREAD

**Issue by DanielLyubin** [QuantumLeaps/qpcpp#8]
Assume there is a child state C and its super state S, and the state machine is in state C (leaf in the state machine graph). Calling isIn(C) and isIn(S) both return true and it's great. When calling super(S) in C and there is a call to isIn(C) from S, assert is called and the program crashes. Same thing for calling isIn(S) from S. Assert is called because of state stability check. However, calling isIn from super states is logically correct, since there is a temporary jump to another state and a transition didn't occur. In other words, being in a super state should not prevent me from calling isIn.

**Comment by quantum-leaps** [comment]
The `isIn()` to query the state of `me` makes no sense, because the state is not well defined during an RTC step (it might be changing as a result of a transition). Therefore, the `isIn()` API is NOT intended to query the state of `me`. It's only intent is to query the state of "Orthogonal Components", and even this should be avoided, as it breaks encapsulation.
--MMS
